### ISSUE TITLE
What is the difference in functionality between this plugin and 'Find All' from the sublime search?

### ISSUE THREAD

**Issue by najamelan** [tarwich/SelectByRegex#3]

**Comment by tarwich** [comment]
This plugin is mostly the same as the _Find All_ functionality of search. The specific focus of this plugin is to speed up the process of selecting all regex matches without using the mouse. You could use only the keyboard for the built-in feature, but it's more complicated to invoke.

I might rewrite this plugin to be a method of invoking the native search with the `select` and `regex` options. Is there a feature you would like to see implemented here that disappointed you?

**Comment by najamelan** [comment]
> Is there a feature you would like to see implemented here that disappointed you?

No, I just didn't figure myself that Find All did this until I searched for it and then I found your plugin, so I read the readme and didn't understand since it seemed like it did the same thing. Personally I don't mind using the mouse, and also selecting by regex is not something that I do everyday, so I was quite happy with what Find All did, it solved my need at the time.
