### ISSUE TITLE
Debounce on_change?

### ISSUE THREAD

**Issue by mreq** [tarwich/SelectByRegex#4]
When using on a big selection, typing in the box triggers the preview on each keypress. When I tried that on 1500ish lines, sublime/python can't handle it.

I'd consider implementing a debounced method, so that the preview updates say 500ms after the last keypress. Opinion? I can write the code and create a pull request if you will.

**Comment by tarwich** [comment]
Go for it. I'm sorry to say that I've joined the Dark Side ([atom.io](https://atom.io/)). It's not Sublime, but it's also not $70.00.

On another note, I've been thinking of making this plugin do nothing more than bring up the _Find_ dialog and set:
- select all
- regular expression
