### ISSUE TITLE
Merge with SublimeSelectRegex?

### ISSUE THREAD

**Issue by mvoidex** [tarwich/SelectByRegex#5]
Hi. I've already had similar non-publised plugin: https://github.com/mvoidex/SublimeSelectRegex, which is very similar to your plugin, but have some differences and advantages:
- Allows selecting group, not full regex
- Allows matching for selected text (`foo$_` matches `foobar` if `bar` was selected)
- Can select next regex or all regexes
- This works well: https://github.com/tarwich/SelectByRegex/issues/4
- But 'select regex: all' differs: it selects all regexes in selection without restriction to single line, so if you want to select regexes in lines, you have to use 'expand selection to line' command

Having two similar plugins is not good idea, can we merge them somehow?

**Comment by tarwich** [comment]
We should probably just delist mine. I think I have to clone the other repo and make a pull request with mine removed. Whatever you need, just let me know. I'm not maintaining this plugin anymore.

**Comment by mvoidex** [comment]
Ok, I can delist it in pull request with my plugin added. You'll have to confirm it in comments. I'll give link here when ready

**Comment by tarwich** [comment]
w00+! Thanks!

**Comment by tarwich** [comment]
PS: Did you want my name? (SelectByRegex) or do you want to keep yours?

**Comment by mvoidex** [comment]
I think I'll keep mine, because i don't understand, what will package control do, if I take yours. Will it replace package on update (which may not be good)?

**Comment by mvoidex** [comment]
Thanks for help, my plgun have been added to package control

**Comment by tarwich** [comment]
Congrats! I see it's replaced mine.

https://packagecontrol.io/packages/Select%20By%20Regex

Well done.
